package com.maoozos.app;

import android.Manifest;
import android.app.AlarmManager;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import org.json.JSONArray;
import org.json.JSONObject;
import java.text.DateFormat;
import java.util.Date;

public class MainActivity extends android.app.Activity {
    private AppStore store;
    private LinearLayout content, nav;
    private TextView title, status;
    private EditText search;
    private int bg = Color.rgb(8,12,20), card = Color.rgb(18,25,38), text = Color.rgb(242,246,255), muted = Color.rgb(154,169,193), accent = Color.rgb(110,168,255);

    @Override protected void onCreate(Bundle b) {
        super.onCreate(b);
        store = new AppStore(this);
        NotificationHelper.ensureChannel(this);
        buildShell();
        if (!store.tourSeen()) showTour(); else showDashboard();
    }

    private int dp(int v){ return (int)(v*getResources().getDisplayMetrics().density+.5f); }
    private TextView tv(String s,float sp, int c){ TextView t=new TextView(this); t.setText(s); t.setTextSize(sp); t.setTextColor(c); t.setPadding(dp(2),dp(2),dp(2),dp(2)); return t; }
    private Button btn(String s){ Button b=new Button(this); b.setText(s); b.setTextColor(text); b.setTextSize(12); b.setAllCaps(false); b.setBackgroundColor(Color.TRANSPARENT); return b; }
    private LinearLayout column(){ LinearLayout l=new LinearLayout(this); l.setOrientation(LinearLayout.VERTICAL); l.setPadding(dp(14),dp(10),dp(14),dp(18)); return l; }
    private LinearLayout card(){ LinearLayout l=column(); l.setBackgroundColor(card); l.setElevation(dp(3)); LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2); p.setMargins(0,dp(7),0,dp(7)); l.setLayoutParams(p); return l; }

    private void buildShell(){
        LinearLayout root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(bg);
        LinearLayout top=new LinearLayout(this); top.setGravity(Gravity.CENTER_VERTICAL); top.setPadding(dp(10),dp(8),dp(10),dp(8));
        TextView brand=tv("MaoozOS",20,Color.WHITE); brand.setTypeface(null,1); top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));
        search=new EditText(this); search.setHint("Search everything..."); search.setTextColor(text); search.setHintTextColor(muted); search.setSingleLine(true); search.setPadding(dp(12),0,dp(12),0); search.setBackgroundColor(Color.rgb(28,38,56));
        top.addView(search,new LinearLayout.LayoutParams(dp(210),dp(46)));
        search.setOnEditorActionListener((v,a,e)->{doSearch(search.getText().toString()); return true;});
        root.addView(top);
        HorizontalScrollView hs=new HorizontalScrollView(this); nav=new LinearLayout(this); nav.setOrientation(LinearLayout.HORIZONTAL);
        String[] names={"Home","Academic","Courses","Timetable","Tasks","Grades","Attendance","Notes","Resources","Settings"};
        for(String n:names){ Button b=btn(n); b.setOnClickListener(v->openModule(n)); nav.addView(b,new LinearLayout.LayoutParams(-2,dp(44))); }
        hs.addView(nav); root.addView(hs);
        content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); content.setBackgroundColor(bg); ScrollView sv=new ScrollView(this); sv.setFillViewport(true); sv.addView(content); root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        status=tv("Developed by Muhammad Maooz",10,muted); status.setGravity(Gravity.CENTER); root.addView(status,new LinearLayout.LayoutParams(-1,dp(34)));
        setContentView(root);
    }

    private void clear(String h){ content.removeAllViews(); title=tv(h,27,text); title.setTypeface(null,1); content.addView(title); }
    private void addHeader(String h,String sub){ LinearLayout c=card(); c.addView(tv(h,18,text)); c.addView(tv(sub,12,muted)); content.addView(c); }
    private void showDashboard(){ clear("Good evening"); JSONObject p=store.read().optJSONObject("profile"); String name=p==null?"Boss":p.optString("displayName","Boss"); content.addView(tv(name,17,muted)); content.addView(tv(DateFormat.getDateTimeInstance(DateFormat.FULL,DateFormat.SHORT).format(new Date()),11,muted));
        addHeader("Today's Classes","Timetable has priority. Upcoming and active classes appear first."); JSONArray cls=store.read().optJSONArray("classes"); if(cls!=null && cls.length()>0){for(int i=0;i<Math.min(8,cls.length());i++) addDataRow("🕘 "+cls.optJSONObject(i).optString("title","Class"), cls.optJSONObject(i).optString("time",""));} else addDataRow("No classes added yet","Open Timetable → + Add Class");
        addHeader("Deadlines & Assessments","Important items are shown before lower-priority analytics."); JSONArray tasks=store.read().optJSONArray("tasks"); if(tasks!=null && tasks.length()>0){for(int i=0;i<Math.min(6,tasks.length());i++) addDataRow("⏰ "+tasks.optJSONObject(i).optString("title","Task"), tasks.optJSONObject(i).optString("due",""));} else addDataRow("No deadlines yet","Add an assignment or task from Tasks");
        addHeader("Academic Snapshot","Calculated from saved records; missing values are not treated as zero."); content.addView(tv("GPA / CGPA: configure grades to calculate",13,text));
    }
    private void addDataRow(String a,String b){ LinearLayout c=card(); LinearLayout row=new LinearLayout(this); row.setOrientation(LinearLayout.VERTICAL); row.addView(tv(a,14,text)); if(!b.isEmpty()) row.addView(tv(b,11,muted)); c.addView(row); content.addView(c); }

    private void openModule(String m){ search.setText(""); switch(m){case "Home":showDashboard();break;case "Academic":academic();break;case "Courses":courses();break;case "Timetable":timetable();break;case "Tasks":tasks();break;case "Grades":grades();break;case "Attendance":attendance();break;case "Notes":notes();break;case "Resources":resources();break;case "Settings":settings();break;} }
    private void academic(){ clear("Academic Profile"); JSONObject r=store.read(); JSONObject p=r.optJSONObject("profile"); EditText name=edit("Display name",p.optString("displayName","Boss")); EditText uni=edit("University",p.optString("university","")); EditText prog=edit("Program",p.optString("program","")); EditText sem=edit("Current semester",String.valueOf(p.optInt("currentSemester",1))); content.addView(name);content.addView(uni);content.addView(prog);content.addView(sem); Button save=btn("Save Academic Profile"); save.setOnClickListener(v->{try{p.put("displayName",name.getText().toString());p.put("university",uni.getText().toString());p.put("program",prog.getText().toString());p.put("currentSemester",Math.max(1,Integer.parseInt(sem.getText().toString().trim())));store.write(r);toast("Academic profile saved");}catch(Exception e){friendlyError("Profile could not be saved",e);}}); content.addView(save); }
    private EditText edit(String hint,String value){ EditText e=new EditText(this); e.setHint(hint);e.setHintTextColor(muted);e.setText(value);e.setTextColor(text);e.setSingleLine(true);e.setPadding(dp(10),dp(6),dp(10),dp(6)); LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(4),0,dp(4));e.setLayoutParams(p);return e; }
    private void courses(){ clear("Courses"); Button add=btn("+ Add Course"); add.setOnClickListener(v->addCourse());content.addView(add); JSONArray a=store.read().optJSONArray("courses"); if(a!=null)for(int i=0;i<a.length();i++){JSONObject c=a.optJSONObject(i);addDataRow("📚 "+c.optString("name","Course"), c.optString("code","")+" • "+c.optString("credits","0")+" credits");}}
    private void addCourse(){ final JSONObject root=store.read(); final JSONArray arr=root.optJSONArray("courses"); final EditText n=edit("Course Name",""); final EditText code=edit("Course Code (optional)",""); final EditText cr=edit("Credit Hours",""); final EditText ins=edit("Instructor (optional)",""); final EditText sec=edit("Section (optional)",""); final EditText sem=edit("Semester","1"); content.addView(n);content.addView(code);content.addView(cr);content.addView(ins);content.addView(sec);content.addView(sem); Button save=btn("Save Course");save.setOnClickListener(v->{try{if(n.getText().toString().trim().isEmpty()){toast("Course name is required");return;}double credits=Double.parseDouble(cr.getText().toString().trim());if(credits<=0)throw new IllegalArgumentException("Credit hours must be positive.");arr.put(new JSONObject().put("id","c"+System.currentTimeMillis()).put("name",n.getText().toString().trim()).put("code",code.getText().toString().trim()).put("credits",credits).put("instructor",ins.getText().toString().trim()).put("section",sec.getText().toString().trim()).put("semester",Math.max(1,Integer.parseInt(sem.getText().toString().trim()))));store.write(root);toast("Course saved");courses();}catch(Exception e){friendlyError("Course could not be saved",e);}});content.addView(save);}
    private void timetable(){ clear("Timetable"); Button add=btn("+ Add Class");add.setOnClickListener(v->addClass());content.addView(add);addDataRow("Timetable URL","Optional • store your university timetable link here");JSONArray a=store.read().optJSONArray("classes");if(a!=null)for(int i=0;i<a.length();i++){JSONObject c=a.optJSONObject(i);addDataRow("🗓 "+c.optString("title","Class"), c.optString("day","")+" • "+c.optString("time","")+" • "+c.optString("room",""));}}
    private void addClass(){final JSONObject root=store.read();final JSONArray arr=root.optJSONArray("classes");EditText title=edit("Course/Class","");EditText day=edit("Day","");EditText time=edit("Time e.g. 10:00-11:30","");EditText room=edit("Room","");EditText type=edit("Type", "Lecture");content.addView(title);content.addView(day);content.addView(time);content.addView(room);content.addView(type);Button save=btn("Save Class");save.setOnClickListener(v->{try{if(title.getText().toString().trim().isEmpty())throw new IllegalArgumentException("Class name is required.");arr.put(new JSONObject().put("id","cl"+System.currentTimeMillis()).put("title",title.getText().toString().trim()).put("day",day.getText().toString().trim()).put("time",time.getText().toString().trim()).put("room",room.getText().toString().trim()).put("type",type.getText().toString().trim()));store.write(root);toast("Class saved");timetable();}catch(Exception e){friendlyError("Class could not be saved",e);}});content.addView(save);}
    private void tasks(){clear("Tasks & Assignments");Button add=btn("+ Add Task");add.setOnClickListener(v->addTask());content.addView(add);JSONArray a=store.read().optJSONArray("tasks");if(a!=null)for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);addDataRow("✅ "+t.optString("title","Task"), t.optString("due","")+" • "+t.optString("priority","Normal"));}}
    private void addTask(){final JSONObject root=store.read();final JSONArray arr=root.optJSONArray("tasks");EditText n=edit("Title","");EditText due=edit("Due date/time","");EditText pri=edit("Priority","Normal");content.addView(n);content.addView(due);content.addView(pri);Button save=btn("Save Task");save.setOnClickListener(v->{try{if(n.getText().toString().trim().isEmpty())throw new IllegalArgumentException("Task title is required.");arr.put(new JSONObject().put("id","t"+System.currentTimeMillis()).put("title",n.getText().toString().trim()).put("due",due.getText().toString().trim()).put("priority",pri.getText().toString().trim()).put("status","not_started"));store.write(root);toast("Task saved");tasks();}catch(Exception e){friendlyError("Task could not be saved",e);}});content.addView(save);}
    private void grades(){clear("Grades / GPA");addHeader("Calculation safety","One native calculation path. Missing grades stay missing; they never become zero.");addDataRow("GPA","Configure course grades and credit hours to calculate");addDataRow("CGPA","Uses saved completed-semester records");}
    private void attendance(){clear("Attendance");addHeader("Attendance safety","No attendance record is treated as an absence.");addDataRow("Current attendance","Add class attendance records to calculate");}
    private void notes(){clear("Notes");Button add=btn("+ Add Note");add.setOnClickListener(v->addNote());content.addView(add);JSONArray a=store.read().optJSONArray("notes");if(a!=null)for(int i=0;i<a.length();i++){JSONObject n=a.optJSONObject(i);addDataRow("📝 "+n.optString("title","Note"), n.optString("content",""));}}
    private void addNote(){final JSONObject root=store.read();final JSONArray arr=root.optJSONArray("notes");EditText title=edit("Title","");EditText body=edit("Content","");body.setSingleLine(false);content.addView(title);content.addView(body);Button save=btn("Save Note");save.setOnClickListener(v->{try{if(title.getText().toString().trim().isEmpty() && body.getText().toString().trim().isEmpty())throw new IllegalArgumentException("Note is empty.");arr.put(new JSONObject().put("id","n"+System.currentTimeMillis()).put("title",title.getText().toString().trim()).put("content",body.getText().toString()));store.write(root);toast("Note saved");notes();}catch(Exception e){friendlyError("Note could not be saved",e);}});content.addView(save);}
    private void resources(){clear("Resources / URLs");Button add=btn("+ Add URL");add.setOnClickListener(v->addResource());content.addView(add);JSONArray a=store.read().optJSONArray("resources");if(a!=null)for(int i=0;i<a.length();i++){JSONObject r=a.optJSONObject(i);addDataRow("🔗 "+r.optString("name",recognize(r.optString("url",""))),r.optString("url",""));}}
    private void addResource(){final JSONObject root=store.read();final JSONArray arr=root.optJSONArray("resources");EditText url=edit("URL","");EditText name=edit("Name (optional)","");content.addView(url);content.addView(name);Button save=btn("Save Resource");save.setOnClickListener(v->{String u=url.getText().toString().trim();if(!(u.startsWith("https://")||u.startsWith("http://"))){toast("Use a normal http:// or https:// URL");return;}try{String n=name.getText().toString().trim();if(n.isEmpty())n=recognize(u);arr.put(new JSONObject().put("id","r"+System.currentTimeMillis()).put("url",u).put("name",n));store.write(root);toast("Resource saved");resources();}catch(Exception e){friendlyError("Resource could not be saved",e);}});content.addView(save);}
    private String recognize(String u){String x=u.toLowerCase();if(x.contains("youtube.com")||x.contains("youtu.be"))return "YouTube (Video)";if(x.contains("github.com"))return "GitHub (Repository)";if(x.contains("docs.google.com"))return "Google Docs (Document)";if(x.contains("drive.google.com"))return "Google Drive";if(x.contains("stackoverflow.com"))return "Stack Overflow";if(x.contains("wikipedia.org"))return "Wikipedia";if(x.contains("leetcode.com"))return "LeetCode";if(x.contains("notion.so"))return "Notion";return "🌐 Website";}
    private void settings(){clear("Settings");Button notify=btn("Notification Settings");notify.setOnClickListener(v->{Intent i=new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName());startActivity(i);});content.addView(notify);Button test=btn("Test Notification");test.setOnClickListener(v->{if(Build.VERSION.SDK_INT>=33 && checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},80);return;}ReminderReceiver.schedule(this,"test"+System.currentTimeMillis(),System.currentTimeMillis()+1200,"MaoozOS test","Notifications are working.");toast("Test notification scheduled");});content.addView(test);Button exact=btn("Exact Reminder Settings");exact.setOnClickListener(v->{if(Build.VERSION.SDK_INT>=31){AlarmManager am=(AlarmManager)getSystemService(ALARM_SERVICE);if(am!=null && !am.canScheduleExactAlarms())startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM));else toast("Exact reminders are already allowed or not required.");}else toast("Exact alarm permission is not required on this Android version.");});content.addView(exact);Button tour=btn("Run App Tour Again");tour.setOnClickListener(v->showTour());content.addView(tour);Button export=btn("Export Full Backup");export.setOnClickListener(v->exportBackup());content.addView(export);Button imp=btn("Import Backup");imp.setOnClickListener(v->importBackup());content.addView(imp);}
    private void doSearch(String q){q=q==null?q.trim():q.trim(); if(q.isEmpty()){toast("Type a search term");return;} JSONObject r=store.read(); StringBuilder out=new StringBuilder(); String[] sections={"courses","tasks","classes","assessments","attendance","notes","resources","semesters"}; for(String s:sections){JSONArray a=r.optJSONArray(s);if(a==null)continue;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);String line=o==null?"":o.toString();if(line.toLowerCase().contains(q.toLowerCase()))out.append("• ").append(s).append(": ").append(line).append("\n\n");}} new AlertDialog.Builder(this).setTitle("Search results").setMessage(out.length()==0?"No matching records found.":out.toString()).setPositiveButton("OK",null).show();}
    private void exportBackup(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"MaoozOS-full-backup.json");startActivityForResult(i,101);}
    private void importBackup(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,102);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data==null||data.getData()==null)return;try{if(req==101){java.io.OutputStream os=getContentResolver().openOutputStream(data.getData());os.write(store.exportJson().getBytes(java.nio.charset.StandardCharsets.UTF_8));os.close();toast("Backup exported");}else if(req==102){java.io.InputStream in=getContentResolver().openInputStream(data.getData());java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);in.close();JSONObject imported=new JSONObject(new String(out.toByteArray(),java.nio.charset.StandardCharsets.UTF_8));if(!imported.has("profile")||!imported.has("courses"))throw new IllegalArgumentException("This is not a valid MaoozOS backup.");if(!store.write(imported))throw new IllegalStateException("Backup could not be saved safely.");toast("Backup imported successfully");showDashboard();}}catch(Exception e){friendlyError(req==102?"Backup was not imported":"Backup was not exported",e);}}
    private void friendlyError(String heading,Exception e){new AlertDialog.Builder(this).setTitle("⚠ "+heading).setMessage((e.getMessage()==null?"Something unexpected happened.":e.getMessage())+"\n\nYour existing data was not intentionally deleted. Try again or use a backup.").setPositiveButton("OK",null).show();}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private void showTour(){ new AlertDialog.Builder(this).setTitle("Welcome to MaoozOS").setMessage("A fast native Android edition focused on smooth performance.\n\n1. Home — classes and deadlines first.\n2. Courses — your academic hubs.\n3. Timetable — native class schedule.\n4. Tasks — assignments and deadlines.\n5. Grades — calculation-safe academic results.\n6. Notes & Resources — offline personal knowledge.\n7. Settings — notifications and full backup/restore.\n\nYou can replay this tour anytime.").setPositiveButton("Start MaoozOS",(d,w)->{store.setTourSeen(true);showDashboard();}).setNegativeButton("Skip",(d,w)->{store.setTourSeen(true);showDashboard();}).show();}
    @Override public void onBackPressed(){showDashboard();}
}
